# Generated by Django 3.2.12 on 2022-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sendmessage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='date',
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
