# Generated by Django 3.2.12 on 2022-03-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220325_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmessage',
            old_name='created_at',
            new_name='send_at',
        ),
    ]
